import json

import frappe

from india_compliance.gst_india.utils.exporter import ExcelExporter


@frappe.whitelist()
def download_books_as_excel(data, company_gstin, month, year):

    filename = ["GSTR-1", "Books", company_gstin, month, year]

    category = [
        "B2B Regular",
        "B2B Reverse Charge",
        "SEZ with Payment of Tax",
        "SEZ without Payment of Tax",
        "Deemed Exports",
        "Export with Payment of Tax",
        "Export without Payment of Tax",
        "B2C (Large)",
        "B2C (Others)",
        "Nil-Rated",
        "Exempted",
        "Non-GST",
        "Credit/Debit Notes (Registered)",
        "Credit/Debit Notes (Unregistered)",
    ]

    excel = ExcelExporter()
    excel.remove_sheet("Sheet")

    data = json.loads(data)

    data = {
        "B2B Regular": [
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
        ],
        "Nil-Rated": [
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
        ],
        "Document Issued": [
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
        ],
        "HSN": [
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
        ],
        "AT": [
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
            {
                "document_type": "Invoice",
                "customer_name": "ELECTROSTEEL CASTINGS LTD",
                "invoice_number": "INV-005",
                "document_date": "2024-04-01",
                "place_of_supply": "01-JHARKHAND",
                "is_reverse_charge": "0",
                "e_commerce_gstin": "01AAACE9602H1Z5",
                "invoice_category": "B2B, SEZ, DE",
                "invoice_sub_category": "Deemed Exports",
                "shipping_bill_number": "123456",
                "shipping_bill_date": "2021-01-05",
                "shipping_port_code": "INMAA1",
            },
        ],
    }

    headers = [
        {
            "fieldname": "document_type",
            "label": "Document Type",
            "width": 100,
        },
        {
            "fieldname": "customer_name",
            "label": "Customer Name",
            "width": 300,
        },
        {
            "fieldname": "invoice_number",
            "label": "Invoice Number",
            "width": 100,
        },
        {
            "fieldname": "document_date",
            "label": "Document Date",
            "width": 90,
        },
        {
            "fieldname": "place_of_supply",
            "label": "Place Of Supply",
            "width": 120,
        },
        {
            "fieldname": "is_reverse_charge",
            "label": "Is Reverse Cgarge",
            "width": 170,
        },
        {
            "fieldname": "e_commerce_gstin",
            "label": "E-commerce GSTIN",
            "width": 170,
        },
        {
            "fieldname": "invoice_category",
            "label": "Invoice Category",
            "width": 170,
        },
        {
            "fieldname": "invoice_sub_category",
            "label": "Invoice Sub Category",
            "width": 170,
        },
        {
            "fieldname": "shipping_bill_number",
            "label": "Shipping Bill Number",
            "width": 170,
        },
        {
            "fieldname": "shipping_bill_date",
            "label": "Shipping Bill Value",
            "width": 170,
        },
    ]

    category_data = []
    for key in category:
        category_data.extend(data.get(key, []))

    excel.create_sheet(
        sheet_name="Sales Invoice",
        headers=headers,
        data=category_data,
        add_totals=False,
    )

    for key in ["AT", "TXP", "HSN", "Document Issued"]:
        excel.create_sheet(
            sheet_name=key,
            headers=headers,
            data=data.get(key, []),
            add_totals=False,
        )

    excel.export(" - ".join(filename))
